using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Reforma.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717144500_ContextNotesMigration")]
    public partial class ContextNotesMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "PrimaryWorkItemId" integer NULL;
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "IssueId" integer NULL;
                ALTER TABLE "Issues" ADD COLUMN IF NOT EXISTS "PrimaryWorkItemId" integer NULL;
                ALTER TABLE "Interventions" ADD COLUMN IF NOT EXISTS "PrimaryWorkItemId" integer NULL;
                ALTER TABLE "Interventions" ADD COLUMN IF NOT EXISTS "AppointmentId" integer NULL;
                ALTER TABLE "BudgetRequests" ADD COLUMN IF NOT EXISTS "PrimaryWorkItemId" integer NULL;
                ALTER TABLE "BudgetRequests" ADD COLUMN IF NOT EXISTS "SourceCommunicationId" integer NULL;
                ALTER TABLE "BudgetRequests" ADD COLUMN IF NOT EXISTS "SourceNoteId" integer NULL;
                ALTER TABLE "BudgetRequests" ADD COLUMN IF NOT EXISTS "SourceTaskId" integer NULL;
                ALTER TABLE "Quotes" ADD COLUMN IF NOT EXISTS "PrimaryWorkItemId" integer NULL;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "PrimaryWorkItemId" integer NULL;
                ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "PrimaryWorkItemId" integer NULL;
                ALTER TABLE "Appointments" ADD COLUMN IF NOT EXISTS "ContactId" integer NULL;
                ALTER TABLE "Communications" ADD COLUMN IF NOT EXISTS "PrimaryWorkItemId" integer NULL;

                CREATE TABLE IF NOT EXISTS "Notes" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ProjectId" integer NOT NULL,
                    "Body" text NOT NULL,
                    "OccurredAt" timestamp with time zone NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    "AuthorUserId" integer NULL,
                    "PrimaryWorkItemId" integer NULL,
                    "PrimaryContactId" integer NULL,
                    "IsPinned" boolean NOT NULL DEFAULT false,
                    "IsDeleted" boolean NOT NULL DEFAULT false,
                    "DeletedAt" timestamp with time zone NULL,
                    "SourceEntityLinkId" integer NULL
                );

                CREATE TABLE IF NOT EXISTS "NoteReferences" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "NoteId" integer NOT NULL,
                    "TargetEntityType" text NOT NULL,
                    "TargetEntityId" integer NOT NULL,
                    CONSTRAINT "FK_NoteReferences_Notes_NoteId" FOREIGN KEY ("NoteId") REFERENCES "Notes" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_NoteReferences_NoteId" ON "NoteReferences" ("NoteId");
                CREATE INDEX IF NOT EXISTS "IX_NoteReferences_TargetEntityType_TargetEntityId" ON "NoteReferences" ("TargetEntityType", "TargetEntityId");

                CREATE TABLE IF NOT EXISTS "RelationMigrationReviews" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ProjectId" integer NOT NULL,
                    "EntityLinkId" integer NOT NULL,
                    "SourceLabel" text NOT NULL,
                    "TargetLabel" text NOT NULL,
                    "OldType" integer NOT NULL,
                    "OldContext" text NULL,
                    "Proposal" text NOT NULL,
                    "Status" text NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "AppliedAtUtc" timestamp with time zone NULL,
                    "CreatedNoteId" integer NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_RelationMigrationReviews_EntityLinkId" ON "RelationMigrationReviews" ("EntityLinkId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "RelationMigrationReviews";
                DROP TABLE IF EXISTS "NoteReferences";
                DROP TABLE IF EXISTS "Notes";
                ALTER TABLE "Communications" DROP COLUMN IF EXISTS "PrimaryWorkItemId";
                ALTER TABLE "Appointments" DROP COLUMN IF EXISTS "ContactId";
                ALTER TABLE "Appointments" DROP COLUMN IF EXISTS "PrimaryWorkItemId";
                ALTER TABLE "Invoices" DROP COLUMN IF EXISTS "PrimaryWorkItemId";
                ALTER TABLE "Quotes" DROP COLUMN IF EXISTS "PrimaryWorkItemId";
                ALTER TABLE "BudgetRequests" DROP COLUMN IF EXISTS "SourceTaskId";
                ALTER TABLE "BudgetRequests" DROP COLUMN IF EXISTS "SourceNoteId";
                ALTER TABLE "BudgetRequests" DROP COLUMN IF EXISTS "SourceCommunicationId";
                ALTER TABLE "BudgetRequests" DROP COLUMN IF EXISTS "PrimaryWorkItemId";
                ALTER TABLE "Interventions" DROP COLUMN IF EXISTS "AppointmentId";
                ALTER TABLE "Interventions" DROP COLUMN IF EXISTS "PrimaryWorkItemId";
                ALTER TABLE "Issues" DROP COLUMN IF EXISTS "PrimaryWorkItemId";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "IssueId";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "PrimaryWorkItemId";
                """);
        }
    }
}
