using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Reforma.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717165000_TaskHierarchyPlanning")]
    public partial class TaskHierarchyPlanning : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "TaskType" integer NOT NULL DEFAULT 0;
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "ParentTaskId" integer NULL;
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "SortOrder" integer NOT NULL DEFAULT 0;
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "ProgressPercent" integer NOT NULL DEFAULT 0;
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "PlannedStartAt" timestamp with time zone NULL;
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "PlannedEndAt" timestamp with time zone NULL;
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "ActualStartAt" timestamp with time zone NULL;
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "ActualEndAt" timestamp with time zone NULL;
                ALTER TABLE "Tasks" ADD COLUMN IF NOT EXISTS "CategoryId" integer NULL;

                UPDATE "Tasks" SET "TaskType" = 0 WHERE "TaskType" IS NULL;
                UPDATE "Tasks" SET "ProgressPercent" = CASE WHEN "Status" = 3 THEN 100 ELSE "ProgressPercent" END;
                UPDATE "Tasks" SET "SortOrder" = "Id" WHERE "SortOrder" = 0;

                CREATE TABLE IF NOT EXISTS "TaskCategories" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ProjectId" integer NOT NULL,
                    "Name" text NOT NULL,
                    "Color" text NULL,
                    "SortOrder" integer NOT NULL DEFAULT 0
                );

                CREATE TABLE IF NOT EXISTS "TaskDependencies" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ProjectId" integer NOT NULL,
                    "PredecessorTaskId" integer NOT NULL,
                    "SuccessorTaskId" integer NOT NULL,
                    "DependencyType" integer NOT NULL DEFAULT 0
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_TaskDependencies_PredecessorTaskId_SuccessorTaskId" ON "TaskDependencies" ("PredecessorTaskId", "SuccessorTaskId");
                CREATE INDEX IF NOT EXISTS "IX_Tasks_ParentTaskId" ON "Tasks" ("ParentTaskId");
                CREATE INDEX IF NOT EXISTS "IX_Tasks_CategoryId" ON "Tasks" ("CategoryId");

                INSERT INTO "TaskCategories" ("ProjectId", "Name", "Color", "SortOrder")
                SELECT p."Id", seed."Name", NULL, seed."SortOrder"
                FROM "Projects" p
                CROSS JOIN (VALUES
                    ('General', 0),
                    ('Cocina', 1),
                    ('Baño', 2),
                    ('Instalaciones', 3),
                    ('Documentación y trámites', 4),
                    ('Compras y suministros', 5),
                    ('Coordinación de gremios', 6),
                    ('Repasos y defectos', 7),
                    ('Exterior', 8),
                    ('Otros', 9)
                ) AS seed("Name", "SortOrder")
                WHERE NOT EXISTS (
                    SELECT 1 FROM "TaskCategories" c
                    WHERE c."ProjectId" = p."Id" AND c."Name" = seed."Name"
                );
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "TaskDependencies";
                DROP TABLE IF EXISTS "TaskCategories";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "CategoryId";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "ActualEndAt";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "ActualStartAt";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "PlannedEndAt";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "PlannedStartAt";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "ProgressPercent";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "SortOrder";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "ParentTaskId";
                ALTER TABLE "Tasks" DROP COLUMN IF EXISTS "TaskType";
                """);
        }
    }
}
